### ISSUE TITLE
Updating docs for V3 template

### ISSUE THREAD

**Issue by Akash-Mair** [SAFE-Stack/docs#201]
Hey guys!

I've put together a list of pages on the SAFE documentation that will need to be updated/added for the latest template
- [x] Introduction(wording .net core -> .net)
- [x] Quick Start 
- [x] SAFE Stack Overview 
- Components of SAFE
   -  [x] Learn about Fable 
 - The SAFE Template 
    - [x] The FAKE script 
    - [x] Overview(table at bottom) 
- How do I...
   - [x] Upgrade from V2 to V3
   - Build 
      - [x] Remove FAKE from my project 
      - [x] Add build automation 
      - [x] Package my SAFE app for deployment 
      - [x] Support older browsers (LOW PRIORITY)
      - [x] Create a docker image 
   - Dev / Test 
      - [x] Test the Client 
      - [x] Test the Server 
      - [x] Debug a SAFE app
 
   - Client/Server
      - [x] Perform roundtrips with MVU 
      - [x] Handle server errors on the client 
      - [x] Upload file from the client 
      - [x] Serve a file from the back-end 
   - UI
      - [x] Add FontAwesome support 
      - [x] Add Bulma support 
      - [x] Add Feliz support 
   - Package Management 
      - [x] Migrate to Yarn from NPM
 - FAQ 
     - [x] Moving from dev to prod 
- [x] Moving current docs into a Legacy V2 section (NEW)
- [x] Removing Legacy v1 

- [x]  Compare the generated sitemap with the current sitemap.xml

If I've missed something let me know :)

**Comment by isaacabraham** [comment]
@Akash-Mair are there no changes needed to recipes that e.g. reference Fulma styles etc. (we're now on Feliz)?

**Comment by Akash-Mair** [comment]
Hey @isaacabraham @theimowski @Zaid-Ajaj 

Just wanted to confirm if there is a need to update the 'Support for older browsers' recipe as we no longer require Babel - https://github.com/SAFE-Stack/SAFE-template/pull/415#issuecomment-850851298. If not we can move it to the Legacy portion of the docs section. 

Thanks!

**Comment by olivercoad** [comment]
Can you please add a task at the end to compare the generated sitemap with the current [sitemap.xml](https://github.com/SAFE-Stack/docs/blob/b16761a32ec0cc558b2fc4907f40be137c52d60e/sitemap.xml) just before merging? To make sure no paths get removed.

When I first started with Fable there were so many broken links between different blog posts and documentation and it was quite frustrating.

**Comment by olivercoad** [comment]
I just compared the [current sitemap](https://github.com/SAFE-Stack/docs/blob/5aac22c5edadd3ea77aeb64fdbf170b5b9cc41cc/sitemap.xml) with the [previous sitemap](https://github.com/SAFE-Stack/docs/blob/b16761a32ec0cc558b2fc4907f40be137c52d60e/sitemap.xml) and it turns out a number of pages *were* removed:

 - http://safe-stack.github.io/docs/legacy-feature-debugging/
 - http://safe-stack.github.io/docs/legacy-template-appservice/
 - http://safe-stack.github.io/docs/legacy-template-azure-ai/
 - http://safe-stack.github.io/docs/legacy-template-azure-registration/
 - http://safe-stack.github.io/docs/legacy-template-docker/
 - http://safe-stack.github.io/docs/legacy-template-gcp-appengine/
 - http://safe-stack.github.io/docs/legacy-template-gcp-kubernetes/
 - http://safe-stack.github.io/docs/legacy-template-google-cloud/
 - http://safe-stack.github.io/docs/legacy-template-heroku/
 - http://safe-stack.github.io/docs/legacy-template-iis/
 - http://safe-stack.github.io/docs/legacy-template-overview/
 - http://safe-stack.github.io/docs/recipes/build/support-older-browsers/
 - http://safe-stack.github.io/docs/recipes/package-management/migrate-to-yarn/
 - http://safe-stack.github.io/docs/recipes/upgrading/v1-to-v2/
 - http://safe-stack.github.io/docs/template-fake/

**Comment by isaacabraham** [comment]
All of the v1 content is gone, yes - the legacy folder contains the v2 content.

We could split the "legacy" bit into two folders, v1 and v2?
